name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build static Linux binaries
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go mod tidy
          mkdir -p build
          for pkg in $(go list ./...); do
            bin=$(basename "$pkg")
            go build -v \
              -trimpath \
              -ldflags "-s -w -extldflags '-static'" \
              -o build/"${bin}-${{ matrix.arch }}" \
              "$pkg"
          done

      - name: List build folder
        run: |
          echo "Contents of $GITHUB_WORKSPACE/build:"
          ls -l build

      - name: Run tests
        run: go test -v ./...

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: build/