jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build static binaries into build/
        env:
          CGO_ENABLED: 0
        run: |
          go mod tidy
          mkdir -p build
          for pkg in $(go list ./...); do
            bin=$(basename "$pkg")
            GOOS=linux GOARCH=amd64 go build -v -o build/"$bin" "$pkg"
          done

      - name: List build folder
        run: ls -l build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: build/
