name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build into build/
        run: |
          go mod tidy
          mkdir -p build
          # build everything under ./... into build/, naming binaries by package path
          for pkg in $(go list ./...); do
            bin=$(basename "$pkg")
            go build -v -o build/"$bin" "$pkg"
          done

      - name: List build folder
        run: |
          echo "Contents of $GITHUB_WORKSPACE/build:"
          ls -l build

      - name: Run tests
        run: go test -v ./...

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-build
          path: build/
